#Organining/Parsing the csv files to better predict fights


#PARSING ALIKE OPENENTS BETWEEN FIGHTER RED AND BLUE

#PARSING OPENENT RECORDS BETWEEN FIGHTERS

#PARSING ELITE FIGHTERS (>=25 WINS <5 LOSSES)

#PASSRING ELITE WRESTERS ()

#PARSING ELITE STRCERS()

#PARSING FIGHTER STRENGTHS:
#FIGHTER STYLE
#does the fighter have more KOs then 

#FIGHTER WEAKNESSES

#MAPPING FIGHTERS A STRENGTHS TO FIGHTERS BS WEAKNESSES 